### PR TITLE
layout issue fixed

### PR DESCRIPTION
**Pull request by ijameelkhan**
This fixes the issue #22 i reported.

### CODE REVIEW

**Comment by ijameelkhan** [comment]
This fixes issue #21

**Comment by arrouse** [comment]
Thanks for the PR @ijameelkhan do you think you can re-open this against develop?

**Comment by ijameelkhan** [comment]
I wont be able to for next couple of days :(  , i think merge it into master and we should be fine.

**Comment by mr-fixit** [comment]
This pull request is being closed without merging because
1) it was asking to merge into master instead of develop
2) it contained many more lines of code than were required to fix the issue.

The fix was moved into a new branch, and will be merged via PR #32

**Pull request closed without merging**
